### ISSUE TITLE
Non Fatal Warning in console

### ISSUE THREAD

**Issue by subatomicceo** [gantrim/meteor-materialize-stylus#1]
Just wondering about this console log that showed up after installing. Thoughts?

"Velocity is already loaded. You may be needlessly importing Velocity again; note that Materialize includes Velocity."

**Comment by gantrim** [comment]
Hey there, First I'd like to thank you for using my package.

Secondly, this usually means that velocity is either directly or indirectly being loaded.
Check your installed packages for velocityjs:velocityjs or other variants. If not found, could you please post your list of installed packages here? Velocity may be loading as a dependency of another installed package. I may need to look into disabling that warning...

**Comment by gantrim** [comment]
no response from op. closing issue.
